### ISSUE TITLE
Uploading images broken using CMB2 media upload button on edit term screen.

### ISSUE THREAD

**Issue by mattheu** [humanmade/smart-media#7]
Bit of an edge case this one!

We have a CMB2 media upload button on the term edit screen. When using this you cannot upload images - they just hang - see screenshot:

![image](https://user-images.githubusercontent.com/494927/48843460-0a142a00-ed8f-11e8-9c65-00405e480255.png)

You can upload the same image fine elsewhere - and then select it on the term edit screen - so this isn't a blocker for us at all.

Somewhat related perhaps is issue #3

**Comment by roborourke** [comment]
So just noticed the modal title is "Edit Image" even while the file is uploading. This is because we try to switch to the edit mode on select however if the image is till uploading "you're gonna have a bad time". I think I can prevent the switching easily enough, just need to do the laborious bit of trawling through the events that get triggered to find the right one!

**Comment by roborourke** [comment]
Think this should be fixed in the latest version.
